// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package test.json.domain;

import java.lang.Integer;
import java.lang.Long;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PersistenceContext;
import javax.persistence.Version;
import org.springframework.transaction.annotation.Transactional;
import test.json.domain.UrlMap;

privileged aspect UrlMap_Roo_Entity {
    
    declare @type: UrlMap: @Entity;
    
    @PersistenceContext
    transient EntityManager UrlMap.entityManager;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long UrlMap.id;
    
    @Version
    @Column(name = "version")
    private Integer UrlMap.version;
    
    public Long UrlMap.getId() {
        return this.id;
    }
    
    public void UrlMap.setId(Long id) {
        this.id = id;
    }
    
    public Integer UrlMap.getVersion() {
        return this.version;
    }
    
    public void UrlMap.setVersion(Integer version) {
        this.version = version;
    }
    
    @Transactional
    public void UrlMap.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void UrlMap.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            UrlMap attached = UrlMap.findUrlMap(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void UrlMap.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void UrlMap.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public UrlMap UrlMap.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        UrlMap merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager UrlMap.entityManager() {
        EntityManager em = new UrlMap().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long UrlMap.countUrlMaps() {
        return entityManager().createQuery("SELECT COUNT(o) FROM UrlMap o", Long.class).getSingleResult();
    }
    
    public static List<UrlMap> UrlMap.findAllUrlMaps() {
        return entityManager().createQuery("SELECT o FROM UrlMap o", UrlMap.class).getResultList();
    }
    
    public static UrlMap UrlMap.findUrlMap(Long id) {
        if (id == null) return null;
        return entityManager().find(UrlMap.class, id);
    }
    
    public static List<UrlMap> UrlMap.findUrlMapEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM UrlMap o", UrlMap.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
