// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package test.json.domain;

import java.lang.String;

privileged aspect UrlMap_Roo_JavaBean {
    
    public String UrlMap.getShortUrl() {
        return this.shortUrl;
    }
    
    public void UrlMap.setShortUrl(String shortUrl) {
        this.shortUrl = shortUrl;
    }
    
    public String UrlMap.getLongUrl() {
        return this.longUrl;
    }
    
    public void UrlMap.setLongUrl(String longUrl) {
        this.longUrl = longUrl;
    }
    
}
