// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package test.json.domain;

import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.lang.String;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import test.json.domain.UrlMap;

privileged aspect UrlMap_Roo_Json {
    
    public String UrlMap.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static UrlMap UrlMap.fromJsonToUrlMap(String json) {
        return new JSONDeserializer<UrlMap>().use(null, UrlMap.class).deserialize(json);
    }
    
    public static String UrlMap.toJsonArray(Collection<UrlMap> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<UrlMap> UrlMap.fromJsonArrayToUrlMaps(String json) {
        return new JSONDeserializer<List<UrlMap>>().use(null, ArrayList.class).use("values", UrlMap.class).deserialize(json);
    }
    
}
